name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
<<<<<<< HEAD
      - name: Prepare GitHub Pages
        run: Copy-Item dist/client/_shell.html dist/client/index.html

=======
>>>>>>> 5fb61bbe4094b295f409c0685ae1bd5908710752

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
<<<<<<< HEAD
          path: ./dist/client
=======
          path: ./dist
>>>>>>> 5fb61bbe4094b295f409c0685ae1bd5908710752

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
